services:
    books-app:
        container_name: books-app
        build:
            context: ../../
            dockerfile: ./.docker/php/Dockerfile
        volumes:
                - ../../:/var/www/html
        ports:
        - 8080:80
        environment:
            - APP_ENV=local
        restart: unless-stopped
    db-books:
        image: mysql:5.7
        container_name: db-books
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: 'books'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3333:3306'
        expose:
            - '3333'
        volumes:
            - my-db-books:/var/lib/mysql
volumes:
    my-db-books:
